### ISSUE TITLE
[hotfix] develop 브랜치 삭제 후 다시 만드는 것 논의

### ISSUE THREAD

**Issue by KIMGEEK** [Prosumer-OSS-21/Virtual-Piano#10]
깃 플로우 전략을 따르면 작업할 때 main 브랜치에서 새로운 브랜치를 생성해 작업 후 추가한 기능을 직업 합병하는 것이 아니라 main 브랜치에서 develop 브랜치를 쪼개 냅니다.  develop 브랜치에서 기능을 작업하고 바로 합치는 방식입니다. main 브랜치를 배포와 동시에 개발하기 위해 이렇게 하는 건데 저희 팀은 아직은 개발만 하면 되므로 어떻게 하면 좋을지 회의해야 할 것 같습니다.

**Comment by Eugene-Binary** [comment]
I guess it would be better to delete develop branch.
develop 브랜치를 삭제하는 것이 좋을 것 같습니다.
